# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 06:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.TextField(primary_key=True, serialize=False)),
                ('left_lng', models.FloatField()),
                ('right_lng', models.FloatField()),
                ('top_lat', models.FloatField()),
                ('down_lat', models.FloatField()),
                ('pnts', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326), size=None)),
            ],
        ),
    ]
